branch-defaults:
  master:
    environment: ProductivityApp-dev
global:
  application_name: ProductivityApp
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
