branch-defaults:
<<<<<<< HEAD
  feat57:
    environment: ProductivityApp-dev
  master:
=======
  feat12:
    environment: ProductivityApp-dev
    group_suffix: null
  feat44:
>>>>>>> 6f67336d836fd00acabfa21fe2cc9a769843dbcc
    environment: ProductivityApp-dev
global:
  application_name: ProductivityApp
  default_ec2_keyname: null
<<<<<<< HEAD
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
=======
  default_platform: node.js
>>>>>>> 6f67336d836fd00acabfa21fe2cc9a769843dbcc
  default_region: us-west-2
  profile: eb-cli
  sc: git
